// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ampqjgltgunkvxbbywix.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFtcHFqZ2x0Z3Vua3Z4YmJ5d2l4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3NTc2NTEsImV4cCI6MjA2NjMzMzY1MX0.jn_4XX87N5jBbNIfIanNyi1vCIT7JgTptbq9cUfD6VA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);